apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: smregistrering
  namespace: default
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 3000
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
    paths:
      - kvPath: /azuread/data/dev/creds/smregistrering
        mountPath: /secrets/azuread/smregistrering
      - kvPath: /azuread/data/dev/creds/smregistrering-backend
        mountPath: /secrets/azuread/smregistrering-backend
      - kvPath: /kv/preprod/fss/smregistrering/default
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  ingresses:
    - "https://smregistrering.nais.preprod.local"
  env:
    - name: HOST
      value: https://smregistrering.nais.preprod.local
    - name: PORT
      value: '3000'
    - name: AAD_DISCOVERY_URL
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
    - name: AAD_REDIRECT_URL
      value: https://smregistrering.nais.preprod.local/callback
    - name: DOWNSTREAM_API_PATH
      value: backend
    - name: DOWNSTREAM_API_URL
      value: http://smregistrering-backend/
    - name: MODIACONTEXTHOLDER_PATH
      value: modiacontextholder/api
    - name: MODIACONTEXTHOLDER_URL
      value: http://modiacontextholder-q1.nais.preprod.local/modiacontextholder/api
    - name: REDIS_HOST
      value: smregistrering-redis.default.svc.nais.local
    - name: REDIS_PORT
      value: '6379'
