apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: smregistrering
  namespace: default
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 90
  port: 3000
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
    paths:
      - kvPath: /azuread/data/prod/creds/smregistrering
        mountPath: /secrets/azuread/smregistrering
      - kvPath: /azuread/data/prod/creds/smregistrering-backend
        mountPath: /secrets/azuread/smregistrering-backend
      - kvPath: /kv/prod/fss/smregistrering/default
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  ingresses:
    - "https://smregistrering.nais.adeo.no"
    - "https://smregistrering.intern.adeo.no"
  env:
    - name: HOST
      value: https://smregistrering.nais.adeo.no
    - name: PORT
      value: '3000'
    - name: AAD_DISCOVERY_URL
      value: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/v2.0/.well-known/openid-configuration 
    - name: AAD_REDIRECT_URL
      value: https://smregistrering.intern.adeo.no/callback
    - name: DOWNSTREAM_API_PATH
      value: backend
    - name: DOWNSTREAM_API_URL
      value: http://smregistrering-backend/
    - name: GRAPH_API_CLIENT_ID
      value: https://graph.microsoft.com
    - name: GRAPH_API_SCOPES
      value: https://graph.microsoft.com/.default
    - name: MODIACONTEXTHOLDER_PATH
      value: modiacontextholder/api
    - name: MODIACONTEXTHOLDER_URL
      value: https://modiacontextholder.adeo.no
    - name: REDIS_HOST
      value: smregistrering-redis.default.svc.nais.local
    - name: REDIS_PORT
      value: '6379'
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
