apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: smregistrering
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{image}}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 3000
  liveness:
    path: /api/internal/is_alive
  readiness:
    path: /api/internal/is_ready
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
    sidecar:
      enabled: true
  ingresses:
    - 'https://smregistrering.dev.intern.nav.no'
  env:
    - name: SMREGISTRERING_BACKEND_SCOPE
      value: api://dev-gcp.teamsykmelding.smregistrering-backend/.default
    - name: SMREGISTRERING_BACKEND_HOST
      value: smregistrering-backend.dev.intern.nav.no
    - name: MODIACONTEXTHOLDER_SCOPE
      value: api://dev-fss.personoversikt.modiacontextholder-q1/.default
    - name: MODIACONTEXTHOLDER_HOST
      value: modiacontextholder-q1.dev-fss-pub.nais.io
    - name: RUNTIME_ENVIRONMENT
      value: dev
