apiVersion: networking.k8s.io/v1
kind: 'Ingress'
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: https://smregistrering.intern.dev.nav.no$1$2
  labels:
    app: smregistrering
    team: teamsykmelding
  name: smregistrering-gosys-redirect
  namespace: teamsykmelding
spec:
  ingressClassName: nais-ingress
  rules:
    - host: sykmelding-redirect.intern.dev.nav.no
      http:
        paths:
          - backend:
              service:
                name: smregistrering
                port:
                  number: 80
            path: /smr(/|$)(.*)
            pathType: ImplementationSpecific