import React from 'react';

import FormHeader from './components/FormHeader';

const Form = () => {
    return (
        <>
            <FormHeader />
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
            <div>form</div>
        </>
    );
};

export default Form;
