apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: smregistrering
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{image}}
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 90
  port: 3000
  liveness:
    path: /api/internal/is_alive
  readiness:
    path: /api/internal/is_ready
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
    sidecar:
      enabled: true
  ingresses:
    - 'https://smregistrering.intern.nav.no'
  accessPolicy:
    outbound:
      rules:
        - application: smregistrering-backend
      external:
        - host: modiacontextholder.prod-fss-pub.nais.io
  env:
    - name: SMREGISTRERING_BACKEND_SCOPE
      value: api://prod-gcp.teamsykmelding.smregistrering-backend/.default
    - name: SMREGISTRERING_BACKEND_HOST
      value: smregistrering-backend
    - name: MODIACONTEXTHOLDER_SCOPE
      value: api://prod-fss.personoversikt.modiacontextholder/.default
    - name: MODIACONTEXTHOLDER_HOST
      value: modiacontextholder.prod-fss-pub.nais.io
