name: Deploy Redis to dev
on:
  push:
    branches:
      - "*"
      - "!master"
    path:
      - server/**
      - .github/workflows/deploy-redis-dev.yml
env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/smregistrering:${{ github.sha }}
jobs:
  deploy-redis:
    name: Checkout code and create docker tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Deploy Redis to preprod
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: redis-config.yml
