name: Deploy to dev
on:
  push:
    branches:
      - "*"
      - "!master"
env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/smregistrering:${{ github.sha }}
jobs:
  build-push-deploy:
    name: Checkout code and create docker tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install deps
        run: |
          npm install
      - name: Run tests for server
        run: |
          npm run test
        working-directory: ./server
      - name: Run tests for client
        env:
          CI: true
        run: |
          npm run test
        working-directory: ./client
      - name: Build
        run: |
          npm run build
        working-directory: ./client
